# Java Edition, assuming full charge on hit
javaMeleeWeaponDamageDict = {    
    "wooden sword" : 4,
    "gold sword" : 4,
    "stone sword" : 5,
    "iron sword" : 6,
    "diamond sword" : 7,
    "netherite sword" : 8,
    "wooden shovel" : 2.5,
    "gold shovel" : 2.5,
    "stone shovel" : 3.5,
    "iron shovel" : 4.5,
    "diamond shovel" : 5.5,
    "netherite shovel" : 6.5,
    "wooden pickaxe" : 2,
    "golden pickaxe" : 2,
    "stone pickaxe" : 3,
    "iron pickaxe" : 4,
    "diamond pickaxe" : 5,
    "netherite pickaxe" : 6,
    "wooden axe" : 7,
    "golden axe" : 7,
    "stone axe" : 9,
    "iron axe" : 9,
    "diamond axe" : 9,
    "netherite axe" : 10,
    "wooden hoe" : 1,
    "gold hoe" : 1,
    "stone hoe" : 1,
    "iron hoe" : 1,
    "diamond hoe" : 1,
    "netherite hoe" : 1,
    "trident" : 9,
    "none" : 1
    }
# crits are applied before enchants or armor, but after strength
# bedrock
bedrockMeleeWeaponDamageDict = {
    "wooden sword" : 5,
    "gold sword" : 5,
    "stone sword" : 6,
    "iron sword" : 7,
    "diamond sword" : 8,
    "netherite sword" : 9,
    "wooden shovel" : 2,
    "gold shovel" : 2,
    "stone shovel" : 3,
    "iron shovel" : 4,
    "diamond shovel" : 5,
    "netherite shovel" : 6,
    "wooden pickaxe" : 2,
    "golden pickaxe" : 2,
    "stone pickaxe" : 3,
    "iron pickaxe" : 4,
    "diamond pickaxe" : 5,
    "netherite pickaxe" : 6,
    "wooden axe" : 4,
    "golden axe" : 4,
    "stone axe" : 5,
    "iron axe" : 6,
    "diamond axe" : 7,
    "netherite axe" : 8,
    "wooden hoe" : 2,
    "gold hoe" : 2,
    "stone hoe" : 3,
    "iron hoe" : 4,
    "diamond hoe" : 5,
    "netherite hoe" : 6,
    "trident" : 9,
    "none" : 2
    }
